// Generated by CoffeeScript 1.6.2
var add_menu, use_my_python_data;

use_my_python_data = function(data) {
  return console.log(data);
};

add_menu = function() {
  var exitItem, f_exit, fileItem, menu;

  menu = Ti.UI.createMenu();
  fileItem = Ti.UI.createMenuItem("File");
  f_exit = function() {
    return Ti.App.exit();
  };
  exitItem = fileItem.addItem("Exit", f_exit);
  menu.appendItem(fileItem);
  return Ti.UI.setMenu(menu);
};

add_menu();
