// Generated by CoffeeScript 1.6.2
var add_menu, add_tray, cryptobox_ctrl, f_exit;

f_exit = function() {
  return Ti.App.exit();
};

Ti.API.addEventListener(Ti.EXIT, function() {
  return console.log("bye bye");
});

add_menu = function() {
  var fileItem, menu;

  menu = Ti.UI.createMenu();
  fileItem = Ti.UI.createMenuItem("File");
  fileItem.addItem("Exit", f_exit);
  menu.appendItem(fileItem);
  return Ti.UI.setMenu(menu);
};

add_menu();

add_tray = function() {
  var programTray, tmenu;

  programTray = Ti.UI.addTray("tray_icon.png");
  tmenu = Ti.UI.createMenu();
  tmenu.addItem("Exit", f_exit);
  return programTray.setMenu(tmenu);
};

add_tray();

angular.module("cryptoboxApp", ["cryptoboxApp.base"]);

cryptobox_ctrl = function($scope, memory) {
  $scope.python_version = get_version();
  $scope.handle_change = function() {
    return $scope.yourName = handle($scope.yourName);
  };
  return $scope.file_input_change = function() {
    return py_file_input_change($scope.file_input);
  };
};
