// Generated by CoffeeScript 1.6.2
var add_menu, add_tray, cryptobox_ctrl, f_exit;

f_exit = function() {
  return Ti.App.exit();
};

Ti.API.addEventListener(Ti.EXIT, function() {
  return console.log("Exiting Cryptobox");
});

add_menu = function() {
  var fileItem, menu;

  menu = Ti.UI.createMenu();
  fileItem = Ti.UI.createMenuItem("File");
  fileItem.addItem("Exit", f_exit);
  menu.appendItem(fileItem);
  return Ti.UI.setMenu(menu);
};

add_menu();

add_tray = function() {
  var programTray, tmenu;

  programTray = Ti.UI.addTray("tray_icon.png");
  tmenu = Ti.UI.createMenu();
  tmenu.addItem("Exit", f_exit);
  return programTray.setMenu(tmenu);
};

add_tray();

angular.module("cryptoboxApp", ["cryptoboxApp.base"]);

cryptobox_ctrl = function($scope, memory) {
  $scope.python_version = get_version();
  $scope.handle_change = function() {
    return $scope.yourName = handle($scope.yourName);
  };
  $scope.file_input_change = function() {
    return py_file_input_change($scope.file_input);
  };
  return $scope.open_dialog = function() {
    var cv_open_save_dialog;

    cv_open_save_dialog = function(e) {
      return console.log(e.toString());
    };
    return console.log(Ti.UI.openFolderChooserDialog(cv_open_save_dialog, {
      "title": "Selecteer datamap Cryptobox",
      "path": Ti.Filesystem.getDocumentsDirectory().toString(),
      "default": "Cryptobox"
    }));
  };
};
