// Generated by CoffeeScript 1.6.3
var assert, fs, path;

fs = require("fs");

assert = require('assert');

path = require("path");

exports["hello"] = function() {
  return assert.equal(1, 1);
};

exports["hello2"] = function() {
  return assert.equal(1, 1);
};
