// Generated by CoffeeScript 1.6.3
var assert, fs, path;

fs = require("fs");

assert = require('assert');

path = require("path");

exports["test add spawn cba_main"] = function() {
  var x;
  return x = 4;
};
